services:
  - type: web
    name: kurumsal-tedarikci-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: a04977001@smtp-brevo.com
      - key: SMTP_FROM_EMAIL
        value: yildirimtarhan@tedarikci.org.tr
      - key: SMTP_FROM_NAME
        value: Kurumsal Tedarikci
      - key: PORT
        value: 10000  # Render 10000 portunu kullanÄ±r